# Generated by Django 3.1.3 on 2021-10-10 10:53

import cms.models.pluginmodel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFViewer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_pdfviewer_pdfviewer', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('pdf', models.FileField(upload_to=cms.models.pluginmodel.CMSPlugin.get_media_path, verbose_name='pdf')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
